[package]
name = "aoc-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
regex = { version = "1.11.1", features = ["perf-dfa-full"] }
rust-crypto = "0.2.36"
